name: Test
# This workflow is triggered on pushes to the repository.
on: [push]
jobs:
  test:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v1
      with:
        node-version: "13.x"
    - run: yarn install
    - run: yarn test
